update 2025-02-04 08:39:07

diff --git a/luci-app-openclash/root/etc/init.d/openclash b/luci-app-openclash/root/etc/init.d/openclash
--- a/luci-app-openclash/root/etc/init.d/openclash
+++ b/luci-app-openclash/root/etc/init.d/openclash
@@ -775,17 +775,19 @@ check_core_status()
          fi
       fi
 
-      if [ "$ipv6_mode" -eq 2 ] || [ "$ipv6_mode" -eq 3 ]; then
-         ip -6 rule del oif utun table 2022 >/dev/null 2>&1
-         ip -6 route del default dev utun table 2022 >/dev/null 2>&1
-         ip -6 route add default dev utun table "$PROXY_ROUTE_TABLE"
-         ip -6 rule add fwmark "$PROXY_FWMARK" ipproto icmp table main pref 1888
-         ip -6 rule add fwmark "$PROXY_FWMARK" table "$PROXY_ROUTE_TABLE" pref 1889
-      fi
+      if [ -n "$(pidof clash)" ]; then
+         if [ "$ipv6_mode" -eq 2 ] || [ "$ipv6_mode" -eq 3 ]; then
+            ip -6 rule del oif utun table 2022 >/dev/null 2>&1
+            ip -6 route del default dev utun table 2022 >/dev/null 2>&1
+            ip -6 route add default dev utun table "$PROXY_ROUTE_TABLE"
+            ip -6 rule add fwmark "$PROXY_FWMARK" ipproto icmp table main pref 1888
+            ip -6 rule add fwmark "$PROXY_FWMARK" table "$PROXY_ROUTE_TABLE" pref 1889
+         fi
 
-      ip route add default dev utun table "$PROXY_ROUTE_TABLE"
-      ip rule add fwmark "$PROXY_FWMARK" ipproto icmp table main pref 1888
-      ip rule add fwmark "$PROXY_FWMARK" table "$PROXY_ROUTE_TABLE" pref 1889
+         ip route add default dev utun table "$PROXY_ROUTE_TABLE"
+         ip rule add fwmark "$PROXY_FWMARK" ipproto icmp table main pref 1888
+         ip rule add fwmark "$PROXY_FWMARK" table "$PROXY_ROUTE_TABLE" pref 1889
+      fi
    else
       reg4='^((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.){3}(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])$'
       while ( [ -n "$(pidof clash)" ] && [ "$CORE_HTTP_CODE" != "200" ] && [ "$TUN_WAIT" -le 120 ] && [[ "$lan_ip" =~ $reg4 ]] )
@@ -795,12 +797,17 @@ check_core_status()
          sleep 1
       done >/dev/null 2>&1
       if ! [[ "$lan_ip" =~ $reg4 ]]; then
+         LOG_OUT "Error: LAN IP Address Get Error, Please Check The LAN Interface Setting or Choose the Correct Interface in the Setting!"
          sleep 10
       fi
-      if [ -z "$(pidof clash)" ] || [ "$CORE_HTTP_CODE" != "200" ]; then
-         LOG_OUT "Error: Core Start Failed, Please Check The Log Infos!"
+      if [ "$CORE_HTTP_CODE" != "200" ]; then
+         LOG_OUT "Error: Core Status Abnormal, Please Check The Log Infos!"
          start_fail
       fi
+   fi
+   if [ -z "$(pidof clash)" ]; then
+      LOG_OUT "Error: Core Start Failed, Please Check The Log Infos!"
+      start_fail
    fi
 }
 
@@ -2970,7 +2977,7 @@ get_config()
    enable_respect_rules=$(uci -q get openclash.config.enable_respect_rules || echo 0)
    intranet_allowed_wan_name=$(uci -q get openclash.config.intranet_allowed_wan_name || echo 0)
    custom_fakeip_filter_mode=$(uci -q get openclash.config.custom_fakeip_filter_mode || echo "blacklist")
-   iptables_compat=$(iptables -m owner -h 2>/dev/null | grep "owner match options" || echo 0)
+   iptables_compat=$(iptables -m owner -h 2>/dev/null | grep "owner match options" || command -v fw4 || echo 0)
    [ -z "$dns_port" ] && dns_port=7874 && uci -q set openclash.config.dns_port=7874
    uci -q commit openclash
 }
